### ISSUE TITLE
Free Traffic

### ISSUE THREAD

**Issue by supersh86** [cdnbye/hlsjs-p2p-engine#55]
Good afternoon, I noticed a change in the OMS. I understand correctly that now we have to pay for our users' p2p traffic?

**Comment by kyle170** [comment]
I would like to also chime in and say that your going to loose a lot of developers and websites if you charge for p2p traffic.

**Comment by snowinszu** [comment]
Dear user,
Thank you for your continuous trust and support of CDNBye.

Since the launch of our products, we have gained recognition and word-of-mouth from various popular streaming media websites and individual developers. The users of our platform have been on the increase day by day. In order to provide better services, our team has been making efforts to iterate and optimize our products to improve the performance.

However, the higher costs of human and server drive us to think about the sustainability of our platform. After discussion and evaluation, our team decides to start the paid service from April 22, and the revenue would be mainly used to cover the labor and server costs. Meanwhile, free service would be still provided for small streaming websites.

The adjusted charge mode is as follows.
- P2P service will be no longer provided for those who do not bind domain names.
- A daily free 10GB of P2P traffic will be provided after the domain name is bound in the console (https://oms.cdnbye.com). Please note that it will be cleared the next day.
- A daily free 40GB of P2P traffic will be provided after signing in at the console. Please note that it will be cleared the next day.
- P2P service will be stopped if the free quota is exceeded. If you want to continue to use it, you need to buy a traffic package.

For traffic package, please log in https://oms.cdnbye.com, click the left bottom to buy the traffic package. Alipay and Paypal are available.

Our official document address is https://docs.cdnbye.com

If you have any questions, please send an email to service@cdnbye.com
Best regards!

**Comment by supersh86** [comment]
Paying for user traffic, considering its unpredictability, is not a good idea.
Unfortunately, I switched to https://github.com/Novage/p2p-media-loader
Suddenly there I got a better experience using p2p technology. On popular vods, it is possible to connect with 100 users, and the percentage of p2p is higher than yours. All opensource including tracker.
